apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ws3190bc9-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:5366294f98ff402bb8df2fc8cb8dea6721ee3de6@sha256:e51889cd2fa66f1a18bac6d845cfcd623d00a8ad54941c43a0028766ce1926a5
          name: container-image
