apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ws3190bc9-java-springboot-gitops
  description: This is GitOps manifest for ws3190bc9-java-springboot   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=ws3190bc9-java-springboot
    backstage.io/kubernetes-id: ws3190bc9-java-springboot 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ws3190bc9-java-springboot
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ws3190bc9-java-springboot
